name: Project_Catalog
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  nb_utils: ^3.3.0+13
  flutter_svg: ^0.19.3
  flutter_statusbarcolor: 0.2.3
  splash_screen_view: ^1.0.1
  http: ^0.12.2
  rxdart: ^0.26.0
  flutter_localizations:
    sdk: flutter
  provider:
  
dev_dependencies:
  build_runner: ^1.11.1
  mobx_codegen: ^1.1.2
  flutter_html: 0.8.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true  

  assets:
    - logo_demo.png
    - back.png
    - lang/en.json
    - Home_Icon.svg
    - About_Icon.svg
    - Search_Icon.svg
    - Bluetooth_Icon.png
    - Medical_Icon.png
    - IOT_Icon.png
    - scr1.jpg
    - scr2.jpg
    - scr3.jpg
    - scr4.jpg
    - scr5.jpg
    - scr6.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
    - family: Jost
      fonts:
        - asset: fonts/Jost-Bold.ttf
        - asset: fonts/Jost-Italic.ttf
        - asset: fonts/Jost-Medium.ttf
        - asset: fonts/Jost-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf

    
